"""inital setup

Revision ID: 801512ea833b
Revises: 
Create Date: 2020-05-11 13:36:44.760598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801512ea833b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'category', 'questions', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'category', 'questions', 'categories', ['category'], ['id'], onupdate=u'CASCADE', ondelete=u'SET NULL')
    # ### end Alembic commands ###
